
services:
  app:
    build:
      context: .Docker.local
    image: supplio-app:latest
    container_name: supplio-app
    user: "${UID}:${GID}"
    depends_on:
      - db
      - minio
      - mailhog
    networks:
      - supplio-external
      - supplio-internal
    environment:
      RAILS_ENV: development
      DB_PORT: 5432
      DATABASE_URL: postgres://postgres:password@db:5432/supplio_development
      MINIO_ENDPOINT: http://minio:19000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    command: >
      /bin/sh -c "bin/rails db:create db:migrate && bin/rails server -b 0.0.0.0"

  db:
    image: postgres:16
    container_name: supplio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supplio_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - supplio-internal

  minio:
    image: minio/minio
    container_name: supplio-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "19000:9000"
    command: server /data

  mailhog:
    image: mailhog/mailhog
    container_name: supplio-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
  minio_data:
networks:
  supplio-external:
    external: true
  supplio-internal:  # ここで supplio-internal ネットワークを定義
    internal: true